# Generated by Django 3.2.11 on 2022-06-11 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=125)),
                ('user', models.CharField(max_length=125)),
                ('created_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'activity_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'business_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mill_name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'mill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comments', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('priority_level', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('image_complete', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'plant_tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
                ('created_by', models.CharField(max_length=125)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('shift', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=500)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('assigned_date', models.DateTimeField(default=datetime.datetime(2022, 6, 11, 12, 28, 58, 530495))),
                ('shift', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 6, 11, 12, 28, 58, 530495), null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('comment', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('priority_level', models.BigIntegerField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('photo_varying', models.TextField(blank=True, null=True)),
                ('is_handover', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHandover',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('handover_date', models.DateTimeField()),
                ('handover_pic', models.CharField(max_length=125)),
                ('handover_remark', models.CharField(max_length=125)),
                ('handover_assigned_by', models.IntegerField()),
                ('created_by', models.CharField(max_length=125)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'task_handover',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('username', models.CharField(max_length=125)),
                ('password', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=125)),
                ('contact', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
